import type { Permission } from "./permissions";
import { ALL_PERMISSIONS } from "./permissions";
import type { RoleType } from "./roles";

/**
 * The starting permission matrix copied into org_role_permissions when an
 * organization is provisioned.
 *
 * These are DEFAULTS, not policy (ADR-011). Once copied, the org owns its rows
 * and may edit them; changing this file never alters an existing org. Two
 * trusts running the same software can disagree about whether a class teacher
 * may edit marks, and both are right.
 *
 * The bias here is conservative: grant what the role obviously needs, and let
 * an admin widen it deliberately rather than discovering later that everyone
 * could approve refunds.
 */
export const DEFAULT_ROLE_PERMISSIONS: Record<RoleType, Permission[]> = {
  // Full control of the tenant. The only role that may edit the permission
  // matrix itself or create schools.
  org_admin: ALL_PERMISSIONS,

  // Runs one school end to end, but cannot reshape the org or rewrite the
  // permission matrix — that stays with the trust.
  principal: [
    "school:read",
    "school:update",
    "school_settings:read",
    "school_settings:update",
    "org_settings:read",
    "class:create",
    "class:read",
    "class:update",
    "class:delete",
    "section:create",
    "section:read",
    "section:update",
    "section:delete",
    "subject:create",
    "subject:read",
    "subject:update",
    "subject:delete",
    "academic_year:create",
    "academic_year:read",
    "academic_year:update",
    "enrollment:create",
    "enrollment:read",
    "enrollment:update",
    "student:create",
    "student:read",
    "student:update",
    "student:delete",
    "student:export",
    "staff:create",
    "staff:read",
    "staff:update",
    "staff:delete",
    "staff:export",
    "leave:read",
    "leave:approve",
    "leave:update",
    "attendance:read",
    "attendance:update",
    "attendance:export",
    "marks:read",
    "marks:update",
    "marks:publish",
    "marks:export",
    "report_card:read",
    "report_card:publish",
    "report_card:export",
    "exam:create",
    "exam:read",
    "exam:update",
    "exam:delete",
    "exam:publish",
    "timetable:create",
    "timetable:read",
    "timetable:update",
    "timetable:delete",
    "syllabus:create",
    "syllabus:read",
    "syllabus:update",
    "syllabus:delete",
    "homework:read",
    "announcement:create",
    "announcement:read",
    "announcement:update",
    "announcement:delete",
    "announcement:publish",
    "fee_head:read",
    "fee_structure:read",
    "fee_payment:read",
    "fee_payment:approve",
    "fee_waiver:read",
    "fee_waiver:approve",
    "fee_refund:read",
    "fee_refund:approve",
    "fee_report:read",
    "fee_report:export",
    "student_fee_assignment:read",
    "role_assignment:read",
    "role_assignment:assign",
    "role_assignment:revoke",
    "portal_access:read",
    "portal_access:grant",
    "portal_access:revoke",
  ],

  // Deputises for the principal on academics. No financial approvals and no
  // ability to grant roles — those stay with the principal.
  vice_principal: [
    "school:read",
    "school_settings:read",
    "class:read",
    "class:update",
    "section:read",
    "section:update",
    "subject:read",
    "academic_year:read",
    "enrollment:read",
    "enrollment:update",
    "student:create",
    "student:read",
    "student:update",
    "student:export",
    "staff:read",
    "leave:read",
    "leave:approve",
    "attendance:read",
    "attendance:update",
    "attendance:export",
    "marks:read",
    "marks:update",
    "marks:publish",
    "marks:export",
    "report_card:read",
    "report_card:export",
    "exam:create",
    "exam:read",
    "exam:update",
    "timetable:create",
    "timetable:read",
    "timetable:update",
    "syllabus:read",
    "syllabus:update",
    "homework:read",
    "announcement:create",
    "announcement:read",
    "announcement:publish",
    "fee_report:read",
    "role_assignment:read",
    "portal_access:read",
  ],

  // Owns a class: marks its attendance, enters its marks, sees its fee status
  // so they can chase defaulters. Cannot publish results — publication is a
  // school-level act (hard rule 8).
  class_teacher: [
    "student:read",
    "student:export",
    "enrollment:read",
    "attendance:create",
    "attendance:read",
    "attendance:update",
    "attendance:export",
    "marks:create",
    "marks:read",
    "marks:update",
    "marks:export",
    "report_card:read",
    "homework:create",
    "homework:read",
    "homework:update",
    "homework:delete",
    "timetable:read",
    "syllabus:read",
    "exam:read",
    "announcement:create",
    "announcement:read",
    "class:read",
    "section:read",
    "subject:read",
    "student_fee_assignment:read",
    "fee_payment:read",
    "leave:create",
    "leave:read",
  ],

  // Teaches a subject to specific sections. Marks and homework for their own
  // sections only — the scope of the assignment, not this list, is what limits
  // them to those sections.
  subject_teacher: [
    "student:read",
    "attendance:create",
    "attendance:read",
    "marks:create",
    "marks:read",
    "marks:update",
    "homework:create",
    "homework:read",
    "homework:update",
    "homework:delete",
    "timetable:read",
    "syllabus:read",
    "exam:read",
    "announcement:read",
    "class:read",
    "section:read",
    "subject:read",
    "leave:create",
    "leave:read",
  ],

  // Collects money and runs the fee ledger. Deliberately cannot approve its own
  // waivers or refunds — that is the separation of duties an auditor looks for.
  accountant: [
    "fee_head:create",
    "fee_head:read",
    "fee_head:update",
    "fee_structure:create",
    "fee_structure:read",
    "fee_structure:update",
    "fee_payment:create",
    "fee_payment:read",
    "fee_payment:update",
    "fee_payment:export",
    "student_fee_assignment:create",
    "student_fee_assignment:read",
    "student_fee_assignment:update",
    "fee_waiver:create",
    "fee_waiver:read",
    "fee_refund:create",
    "fee_refund:read",
    "fee_report:read",
    "fee_report:export",
    "student:read",
    "enrollment:read",
    "class:read",
    "section:read",
    "school:read",
    "announcement:read",
    "leave:create",
    "leave:read",
  ],

  // Library is not built yet (see PRD non-goals). Seeded minimally so the role
  // exists for assignment without implying features that do not ship.
  librarian: [
    "student:read",
    "class:read",
    "section:read",
    "announcement:read",
    "leave:create",
    "leave:read",
  ],

  // HR-side administration across the org: staff records and leave, no
  // academic or financial reach.
  staff_coordinator: [
    "staff:create",
    "staff:read",
    "staff:update",
    "staff:export",
    "leave:create",
    "leave:read",
    "leave:update",
    "leave:approve",
    "school:read",
    "class:read",
    "section:read",
    "announcement:create",
    "announcement:read",
    "role_assignment:read",
  ],
};
